project:
  type: book
  output-dir: docs

book:
  title: "Viewed from Above: An Learning Diary on Remote Sensing & Earth Observation"
  author: "The-Huan Hoang"
  favicon: "images/planet-earth.png"
  navbar:
    logo: "images/planet-earth.png"
    collapse: true
    background: dark
    search: false
    right: 
      - icon: github

  repo-url: https://github.com/hanukikanker/rs-diary
  repo-actions: [issue]
  
  # google-analytics:
  #   tracking-id: "G-5LZK055F2X"
  #   anonymize-ip: true
  # date: "1/19/2023"
  
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    # - week5.qmd # No journal this week
    # - week6.qmd # GEE
    # - week7.qmd # Classification pt 1
    # - week8.qmd # Classification pt 2
    # - week9.qmd # 
    # - glossary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
        light: [journal]
        dark: [journal,darkly]
    code-link: true
  pdf:
    documentclass: scrbook

editor: visual